import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


function Home() {


  const clickButton = async (name, action) => {


    let response = await fetch(`http://localhost:3000/api/${name}?action=${action}`)

    if(response.ok){
      let content = await response.json();

      console.log("response -> ", content);
    }else{
      alert(`deu ruim`);
    }

    alert(`${name} ${action}`);
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Krypton</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Krypton
        </h1>


        <div className={styles.grid}>

          <div className={styles.card}>
            <h2>Amarela - 001</h2>

            <div className={styles.divButtons}>
              <button className={styles.btnOn}
                      onClick={() => clickButton("amarela", 1)}>
                Ligar
              </button>

              <button className={styles.btnOff}
                      onClick={() => clickButton("amarela", 0)}>

                Desligar
              </button>
            </div>

          </div>

          <div className={styles.card}>
            <h2>Azul - 002</h2>

            <div className={styles.divButtons}>
              <button className={styles.btnOn}
                      onClick={() => clickButton("azul", 1)}>
                Ligar
              </button>

              <button className={styles.btnOff}
                      onClick={() => clickButton("azul", 0)}>

                Desligar
              </button>
            </div>

          </div>

          <div className={styles.card}>
            <h2>Verde 1 - 003</h2>

            <div className={styles.divButtons}>
              <button className={styles.btnOn}
                      onClick={() => clickButton("verde01", 1)}>
                Ligar
              </button>

              <button className={styles.btnOff}
                      onClick={() => clickButton("verde01", 0)}>

                Desligar
              </button>
            </div>
          </div>

          <div className={styles.card}>
            <h2>Verde 2 - 004</h2>

            <div className={styles.divButtons}>
              <button className={styles.btnOn}
                      onClick={() => clickButton("verde02", 1)}>
                Ligar
              </button>

              <button className={styles.btnOff}
                      onClick={() => clickButton("verde02", 0)}>

                Desligar
              </button>
            </div>
          </div>

          <div className={styles.card}>
            <h2>Branca - 005</h2>

            <div className={styles.divButtons}>
              <button className={styles.btnOn}
                      onClick={() => clickButton("branca", 1)}>
                Ligar
              </button>

              <button className={styles.btnOff}
                      onClick={() => clickButton("branca", 0)}>

                Desligar
              </button>
            </div>
          </div>

          <div className={styles.card}>
            <h2>Vermelha- 006</h2>

            <div className={styles.divButtons}>
              <button className={styles.btnOn}
                      onClick={() => clickButton("vermelha", 1)}>
                Ligar
              </button>

              <button className={styles.btnOff}
                      onClick={() => clickButton("vermelha", 0)}>

                Desligar
              </button>
            </div>

          </div>

        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}


export default Home;